spring:
#database
  datasource:
    url: jdbc:postgresql://${DATABASE_URL}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    show-sql: true
#liquibase
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

# messages.properties
validation:
  message:
    directory:
      name:
        notEmpty: the folder name cannot be empty
        size: the folder name can be from 1 to 100 characters
    content:
      name:
        notEmpty: the content name cannot be empty
        size: the content name can be from 1 to 100 characters
      link:
        notEmpty: the content link cannot be empty
      comment:
        size: max size comment 2000 chars